export const SET_EXTENSION_ROOM = 'SET_EXTENSION_ROOM';
export const SET_GOOUT_DATE = 'SET_GOOUT_DATE';
export const SET_STAY_TYPE = 'SET_STAY_TYPE';
export const SET_MUSIC_DATE = 'SET_MUSIC_DATE';

export const SELECT_GOINGOUT_CARD = 'SELECT_GOINGOUT_CARD';
export const SELECT_MUSIC_CARD = 'SELECT_MUSIC_CARD';