export const SET_EXTENSION_ROOM = 'SET_EXTENSION_ROOM';
export const SET_GOOUT_DATE = 'SET_GOOUT_DATE';
export const SET_STAY_TYPE = 'SET_STAY_TYPE';
export const SET_MUSIC_DATE = 'SET_MUSIC_DATE';

export const SELECT_GOINGOUT_CARD = 'SELECT_GOINGOUT_CARD';
export const SELECT_MUSIC_CARD = 'SELECT_MUSIC_CARD';

export const SET_SECTION = 'SET_SECTION';
export const SET_MODAL = 'SET_MODAL';

export const IS_LOGIN = 'IS_LOGIN';

export const SET_MEAL_PREV_DATE = 'SET_MEAL_PREV_DATE';
export const SET_MEAL_NEXT_DATE = 'SET_MEAL_NEXT_DATE';
export const SET_MEAL = 'SET_MEAL';
